### PR TITLE
Remove spurious const specifiers

### PR DESCRIPTION
**Pull request by timarmstrong**
This is required to build against more recent versions of the test
harnesses from ASF master

### CODE REVIEW

**Comment by timarmstrong** [comment]
Ping - this is a very small/safe change and should be a quick review

**Comment by lekv** [comment]
LGTM, how did you test this change?

**Comment by timarmstrong** [comment]
I built it locally and ran the tests.

**Comment by lekv** [comment]
Should we open an Impala JIRA to add these steps to our build process, so this doesn't bit-rot again?

**Comment by timarmstrong** [comment]
I filed https://issues.cloudera.org/browse/IMPALA-5026 for that. There are some other issues to deal with as well - this code has diverged in multiple ways from the related code in the Impala source tree.

**Pull request merged**
